//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Article List</summary>
	[PublishedContentModel("articleList")]
	public partial class ArticleList : PublishedContentModel, IMetaDataControls, INavigationControls, IUmbracoUrlAliasControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "articleList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ArticleList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ArticleList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Description: Enter the meta description. This is what shows up in Google etc. If left blank, will use the page name.
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Umbraco.Web.PublishedContentModels.MetaDataControls.GetMetaDescription(this); }
		}

		///<summary>
		/// Meta Keywords: Enter the meta keywords. This is used for Search Engine
		///</summary>
		[ImplementPropertyType("metaKeywords")]
		public IEnumerable<string> MetaKeywords
		{
			get { return Umbraco.Web.PublishedContentModels.MetaDataControls.GetMetaKeywords(this); }
		}

		///<summary>
		/// Meta Name: Enter the meta name. If left blank it will use the page name.
		///</summary>
		[ImplementPropertyType("metaName")]
		public string MetaName
		{
			get { return Umbraco.Web.PublishedContentModels.MetaDataControls.GetMetaName(this); }
		}

		///<summary>
		/// Disable Dropdown: Tick this box if you want to disable the dropdown for this item
		///</summary>
		[ImplementPropertyType("disableDropdown")]
		public bool DisableDropdown
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationControls.GetDisableDropdown(this); }
		}

		///<summary>
		/// Text Only In Navigation: Tick this box if you want this item to be just text only in the navigation menu.
		///</summary>
		[ImplementPropertyType("textOnlyInNavigation")]
		public bool TextOnlyInNavigation
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationControls.GetTextOnlyInNavigation(this); }
		}

		///<summary>
		/// Umbraco Navi Hide: Tick this box if you want to hide it from the site.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.NavigationControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Umbraco Url Alias: Enter an alternate url in here. Please note that the values you use must be lowercase, not use a leading slash and not use a trailing ".aspx" or trailing slash. If you are adding multiple values, they must be separated with a comma.
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return Umbraco.Web.PublishedContentModels.UmbracoUrlAliasControls.GetUmbracoUrlAlias(this); }
		}
	}
}
