//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Carousel Slide</summary>
	[PublishedContentModel("carouselSlide")]
	public partial class CarouselSlide : PublishedContentModel, IDisableControls, ISlideImageControls, ISlideLinkControls, ISlideSubtitleControls, ISlideTitleControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "carouselSlide";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CarouselSlide(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CarouselSlide, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Disabled: Tick this box if you want to disable/hide this item
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return Umbraco.Web.PublishedContentModels.DisableControls.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Slide Image: Add an image for the slide
		///</summary>
		[ImplementPropertyType("slideImage")]
		public IPublishedContent SlideImage
		{
			get { return Umbraco.Web.PublishedContentModels.SlideImageControls.GetSlideImage(this); }
		}

		///<summary>
		/// Slide Link: Add a link for this slide to link to
		///</summary>
		[ImplementPropertyType("slideLink")]
		public Umbraco.Web.Models.RelatedLinks SlideLink
		{
			get { return Umbraco.Web.PublishedContentModels.SlideLinkControls.GetSlideLink(this); }
		}

		///<summary>
		/// Slide Subtitle: Enter the subtitle for this slide
		///</summary>
		[ImplementPropertyType("slideSubtitle")]
		public string SlideSubtitle
		{
			get { return Umbraco.Web.PublishedContentModels.SlideSubtitleControls.GetSlideSubtitle(this); }
		}

		///<summary>
		/// Slide Title: Enter the title for this slide
		///</summary>
		[ImplementPropertyType("slideTitle")]
		public string SlideTitle
		{
			get { return Umbraco.Web.PublishedContentModels.SlideTitleControls.GetSlideTitle(this); }
		}
	}
}
