//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1076 with alias "footerContentControls"
	/// <summary>Footer Content Controls</summary>
	public partial interface IFooterContentControls : IPublishedContent
	{
		/// <summary>Footer Links</summary>
		Umbraco.Web.Models.RelatedLinks FooterLinks { get; }

		/// <summary>Footer Social Links</summary>
		Umbraco.Web.Models.RelatedLinks FooterSocialLinks { get; }

		/// <summary>Footer Title</summary>
		string FooterTitle { get; }
	}

	/// <summary>Footer Content Controls</summary>
	[PublishedContentModel("footerContentControls")]
	public partial class FooterContentControls : PublishedContentModel, IFooterContentControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footerContentControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FooterContentControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FooterContentControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Links: Enter the footer links
		///</summary>
		[ImplementPropertyType("footerLinks")]
		public Umbraco.Web.Models.RelatedLinks FooterLinks
		{
			get { return GetFooterLinks(this); }
		}

		/// <summary>Static getter for Footer Links</summary>
		public static Umbraco.Web.Models.RelatedLinks GetFooterLinks(IFooterContentControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("footerLinks"); }

		///<summary>
		/// Footer Social Links: Enter the social links to show in the footer
		///</summary>
		[ImplementPropertyType("footerSocialLinks")]
		public Umbraco.Web.Models.RelatedLinks FooterSocialLinks
		{
			get { return GetFooterSocialLinks(this); }
		}

		/// <summary>Static getter for Footer Social Links</summary>
		public static Umbraco.Web.Models.RelatedLinks GetFooterSocialLinks(IFooterContentControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("footerSocialLinks"); }

		///<summary>
		/// Footer Title: Enter a title for the footer content
		///</summary>
		[ImplementPropertyType("footerTitle")]
		public string FooterTitle
		{
			get { return GetFooterTitle(this); }
		}

		/// <summary>Static getter for Footer Title</summary>
		public static string GetFooterTitle(IFooterContentControls that) { return that.GetPropertyValue<string>("footerTitle"); }
	}
}
