//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1077 with alias "latestArticlesControls"
	/// <summary>Latest Articles Controls</summary>
	public partial interface ILatestArticlesControls : IPublishedContent
	{
		/// <summary>Latest Articles Subtitle</summary>
		string LatestArticlesSubtitle { get; }

		/// <summary>Latest Articles Title</summary>
		string LatestArticlesTitle { get; }
	}

	/// <summary>Latest Articles Controls</summary>
	[PublishedContentModel("latestArticlesControls")]
	public partial class LatestArticlesControls : PublishedContentModel, ILatestArticlesControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "latestArticlesControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LatestArticlesControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LatestArticlesControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Latest Articles Subtitle: Enter the subtitle for the latest articles
		///</summary>
		[ImplementPropertyType("latestArticlesSubtitle")]
		public string LatestArticlesSubtitle
		{
			get { return GetLatestArticlesSubtitle(this); }
		}

		/// <summary>Static getter for Latest Articles Subtitle</summary>
		public static string GetLatestArticlesSubtitle(ILatestArticlesControls that) { return that.GetPropertyValue<string>("latestArticlesSubtitle"); }

		///<summary>
		/// Latest Articles Title: Enter a title for the latest articles
		///</summary>
		[ImplementPropertyType("latestArticlesTitle")]
		public string LatestArticlesTitle
		{
			get { return GetLatestArticlesTitle(this); }
		}

		/// <summary>Static getter for Latest Articles Title</summary>
		public static string GetLatestArticlesTitle(ILatestArticlesControls that) { return that.GetPropertyValue<string>("latestArticlesTitle"); }
	}
}
