//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1083 with alias "slideLinkControls"
	/// <summary>Slide Link Controls</summary>
	public partial interface ISlideLinkControls : IPublishedContent
	{
		/// <summary>Slide Link</summary>
		Umbraco.Web.Models.RelatedLinks SlideLink { get; }
	}

	/// <summary>Slide Link Controls</summary>
	[PublishedContentModel("slideLinkControls")]
	public partial class SlideLinkControls : PublishedContentModel, ISlideLinkControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "slideLinkControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SlideLinkControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SlideLinkControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Slide Link: Add a link for this slide to link to
		///</summary>
		[ImplementPropertyType("slideLink")]
		public Umbraco.Web.Models.RelatedLinks SlideLink
		{
			get { return GetSlideLink(this); }
		}

		/// <summary>Static getter for Slide Link</summary>
		public static Umbraco.Web.Models.RelatedLinks GetSlideLink(ISlideLinkControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("slideLink"); }
	}
}
